### ISSUE TITLE
No idea what I'm doing

### ISSUE THREAD

**Issue by kevando** [blendlabs/react-native-screenshot-detector#2]
I can't really figure out how to get this to work on ios. Taking screenshot does nothing. Is this correct? cc/ @gcarling 

```javascript
componentDidMount() {
    console.log('RNScreenshotDetector',RNScreenshotDetector);

    RNScreenshotDetector.subscribe(function(){
      alert('screenshot taken!')
      console.log('SUBSCRIBE');
    });

  }
```

**Comment by gcarling** [comment]
Hey @kevando, sorry for the confusion. I have updated the project with a more descriptive README and an Example project. Thanks for your interest in this, and please let me know if you have any other questions!

**Comment by kevando** [comment]
Thanks @gcarling for the update. I got everything working in about 2 minutes. You rock!
