### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by dhorelik** [blendlabs/react-native-screenshot-detector#3]
react-native-screenshot-detector isn't available on npm, so `$ npm install react-native-screenshot-detector --save` doesn't seem to work. There is a way to add it to package.json as `"react-native-screenshot-detector": "git://github.com:blendlabs/react-native-screenshot-detector.git"`, but installing a package would be more convenient and robust (in terms of further updates).

**Comment by gcarling** [comment]
https://www.npmjs.com/package/react-native-screenshot-detector

Done! Thank you for your interest, I meant to do this for a while and appreciate you pushing me to get it done.
